version: '3.8'

services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: dagster-app
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=production
      - PROJECT_NAME=dagster-project
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home
      - ./logs:/app/logs
    networks:
      - dagster-network
    restart: unless-stopped

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: dagster-daemon
    command: ["dagster-daemon", "run"]
    environment:
      - ENVIRONMENT=production
      - PROJECT_NAME=dagster-project
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home
      - ./logs:/app/logs
    depends_on:
      - dagster
    networks:
      - dagster-network
    restart: unless-stopped

volumes:
  dagster_home:

networks:
  dagster-network:
    driver: bridge