version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  info_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/info/app.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
  
  error_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error/error.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
  
  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug/debug.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8

loggers:
  dagster:
    level: INFO
    handlers: [console, info_file]
    propagate: false
  
  asset_discovery:
    level: DEBUG
    handlers: [console, info_file, debug_file]
    propagate: false
  
  my_dagster_project:
    level: INFO
    handlers: [info_file, error_file]
    propagate: false

root:
  level: INFO
  handlers: [console, info_file, error_file]