# Dagster configuration - SQLite version
run_storage:
  module: dagster.core.storage.db_io_manager
  class: SqliteRunStorage
  config:
    base_dir: /opt/dagster/dagster_home

event_log_storage:
  module: dagster.core.storage.event_log
  class: SqliteEventLogStorage
  config:
    base_dir: /opt/dagster/dagster_home

schedule_storage:
  module: dagster.core.storage.schedules
  class: SqliteScheduleStorage
  config:
    base_dir: /opt/dagster/dagster_home

compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: /opt/dagster/dagster_home/compute_logs

local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: /opt/dagster/dagster_home/storage